name: build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2.3.1
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Build
        run: sbt "; test; frontend/fullLinkJS"
      - uses: actions/upload-artifact@v2
        with:
          path: 'frontend/target/scala-*/pushy-reloaded-opt/*'
