name: release

on:
  release:
    types: [ published ]

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.2.0
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Build
        env:
          CI_VERSION: ${{ github.ref }}
        run: sbt "; test; frontend/fullLinkJS"
      - uses: actions/upload-artifact@v4
        with:
          path: 'frontend/target/scala-*/pushy-reloaded-opt/*'
      - uses: AButler/upload-release-assets@v3.0
        with:
          files: 'frontend/target/scala-*/pushy-reloaded-opt/*'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
